require_relative './regis/base'
require_relative "./regis/configuration"
require_relative "./regis/query"
require_relative "./regis/exceptions"
require_relative "./regis/request"
require_relative "./regis/provider"
require_relative "./regis/ip_address"
require_relative './regis/providers/base'
require_relative './regis/providers/google'
require_relative './regis/providers/here'
require_relative './regis/providers/freegeoip'
require_relative './regis/providers/ovi'
require_relative "./regis/results/google"
require_relative "./regis/results/ovi"
require_relative "./regis/results/freegeoip"
